#!/bin/bash
set -euo pipefail

# labextensions
jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension \ 
                            @pyviz/jupyterlab_pyviz

#EOF
